# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1060d266467b65004ca756bdafb3e5dfb5b3f62b77c7006457eca2a0c324ba8bf3fad36af642ced9ff2582e2810983d549982330c2b24aef6782aad86696d61f

test:
  secret_key_base: 91da5ef51632311a996d802ce65d14817a5c0edce845b9229dade82203391b78252ae1ed361759a4c37cdb236625ea45449cb39275ae5304c7b8e0e4c336075d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
